# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f705fe002283f32df5f4271c8175445bf93cd582bfdf5777c89e6b766fd9f87be762360f5502adfb72fc238236a7c32a48fbf510f81ae8b2512067ddc415938

test:
  secret_key_base: 5979e1936ec1922d64f0845303a71eb659e771c79ffeabcaf247a9f6273782dc108edc501128880150b6d3a525d4dc6d7092d3cb7f34f089553ea48a8e37c35c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
